version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: tournament-postgres
    environment:
      POSTGRES_USER: tournament
      POSTGRES_PASSWORD: tournament
      POSTGRES_DB: tournamentdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tournament -d tournamentdb"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
